// MobileTerminalAppDelegate.m
// MobileTerminal

#import "MobileTerminalAppDelegate.h"
#import "MobileTerminalViewController.h"

#import "Preferences/Settings.h"
#import "Preferences/MenuSettings.h"

// Automatically generated by build rules
#import "svnversion.h"


@implementation MobileTerminalAppDelegate

@synthesize window;
@synthesize navigationController;
@synthesize terminalViewController;
@synthesize preferencesViewController;

- (void)applicationDidFinishLaunching:(UIApplication *)application
{
  Settings* settings = [Settings sharedInstance];
  settings.svnVersion = SVN_VERSION;
  
  [[UIApplication sharedApplication] setStatusBarHidden:YES];
  [window addSubview:terminalViewController.view];
  [window makeKeyAndVisible];
}

static const NSTimeInterval kAnimationDuration = 1.00f;

- (void)preferencesButtonPressed
{
  [UIView beginAnimations:NULL context:NULL];
  [UIView setAnimationDuration:kAnimationDuration];
  [UIView setAnimationTransition:UIViewAnimationTransitionFlipFromLeft
                         forView:navigationController.view
                           cache:YES];
  navigationController.visibleViewController.view = preferencesViewController.view;

  [terminalViewController.view removeFromSuperview];
  [window addSubview:navigationController.view];
  [UIView commitAnimations];
}

- (void)preferencesDonePressed:(id)sender;
{
  [[Settings sharedInstance] persist];
  [UIView beginAnimations:NULL context:NULL];
  [UIView setAnimationDuration:kAnimationDuration];
  [UIView setAnimationTransition:UIViewAnimationTransitionFlipFromRight 
                         forView:terminalViewController.view
                           cache:YES];
  [navigationController popViewControllerAnimated:YES];
  [navigationController.view removeFromSuperview];
  [window addSubview:terminalViewController.view];  
  [UIView commitAnimations];
}

- (void)dealloc {
  [terminalViewController release];
  [window release];
  [super dealloc];
}

@end
