include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = NewTermPreferences
NewTermPreferences_FILES = $(wildcard *.[xm])
NewTermPreferences_INSTALL_PATH = /Applications/NewTerm.app/PreferenceBundles
NewTermPreferences_PRIVATE_FRAMEWORKS = Preferences
NewTermPreferences_EXTRA_FRAMEWORKS = Cephei CepheiPrefs

include $(THEOS_MAKE_PATH)/bundle.mk
